# Generated by Django 2.0.7 on 2018-07-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='is_tokened',
            field=models.BooleanField(default=False),
        ),
    ]
